image:
  file: .gitpod.dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
  - port: 4000

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
  # Install front-end assets
  - init: cd /workspace/assets && npm install && node node_modules/webpack/bin/webpack.js --mode development && cd /workspace && mix deps.get && mix ecto.create
    command: mix deps.get && mix ecto.migrate && iex -S mix phx.server

vscode:
  extensions:
    - JakeBecker.elixir-ls@0.2.25:X1tqg5Hmluq055QJpf0/7A==